apiVersion: build.pivotal.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: demo-cluster-builder
spec:
  # gcr.io/paketo-buildpacks/builder:0.0.123-base-platform-api-0.3
  image: gcr.io/paketo-buildpacks/builder@sha256:ecc95ba6ec892eb8e24ac7b0098b5181396f85e14a66f3c53bda8a79e930d4b3
  # ClusterBuilders do not support imagePullSecrets: builder image must be available to kpack without credentials.
  updatePolicy: external   # polling (every 5 min) is default. Use external for manual updates.

