# Base builder supports Java, NodeJS and Golang
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: paketo-base-stack
  # cluster-scoped
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "gcr.io/paketo-buildpacks/build:0.0.15-base-cnb"
  runImage:
#    image: "gcr.io/paketo-buildpacks/run:0.0.15-base-cnb"
    image: "gcr.io/paketo-buildpacks/run:0.0.16-base-cnb"
---
# Tiny builder supports Golang
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: paketo-tiny-stack
  # cluster-scoped
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "gcr.io/paketo-buildpacks/build:0.0.16-tiny-cnb"
  runImage:
#    image: "gcr.io/paketo-buildpacks/run:0.0.28-tiny-cnb"
    image: "gcr.io/paketo-buildpacks/run:0.0.30-tiny-cnb"
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: paketo-store
  # cluster-scoped
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java:1.4.1
    - image: gcr.io/paketo-buildpacks/java:1.4.2
    - image: gcr.io/paketo-buildpacks/go:v0.0.1
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: custom-java-builder
  namespace: kpack-builds
spec:
  tag: docker.io/ciberkleid/custom-java-builder
  serviceAccount: kpack-service-account
  stack: paketo-base-stack
  store: paketo-store
  order:
    - group:
        # meta-buildpack
#        - id: gcr.io/paketo-buildpacks/java:1.4.1
        - id: gcr.io/paketo-buildpacks/java:1.4.2
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: custom-go-builder
  namespace: kpack-builds
spec:
  tag: docker.io/ciberkleid/custom-go-builder
  serviceAccount: kpack-service-account
  stack: paketo-tiny-stack
  store: paketo-store
  order:
    - group:
        # meta-buildpack
        - id: gcr.io/paketo-buildpacks/go:v0.0.1
