apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: hello-box-rebaseable
  namespace: kpack-builds
spec:
  tag: ciberkleid/hello-box:kpack-rebase-demo-latest
  serviceAccount: kpack-service-account
  cacheSize: "1.5Gi" # Set to enable caching
  failedBuildHistoryLimit: 5 # Default is 10
  successBuildHistoryLimit: 5 # Ddefault is 10
  builder:
    name: custom-go-builder
    kind: CustomBuilder
  source:
    git:
      url: https://github.com/ciberkleid/hello-go
      revision: master
      subPath: hello-box
  build:
    env:
      - name: BP_OCI_AUTHORS
        value: me@example.com
      - name: BP_OCI_DOCUMENTATION
        value: "USAGE: Provide a string and we'll say hello! Use env var HELLO_BOX_ARG to provide the string."
        # For base run-image:
        # value: "USAGE: Provide a string and we'll say hello! Use command \"hello-box <string>\" or env var HELLO_BOX_ARG to provide the string."
