@_ECHO_OFF
tabname dockerfile-go
SAVED_DEMO_DELAY=${DEMO_DELAY}
export BAT_LANG_FLAG="-l Dockerfile"
export DOCKER_BUILDKIT=0
dclean
cd ${DEMO_TEMP}

# Set up demo files
go clean -x -modcache
if [ ! -d hello-go ]; then git clone git@github.com:ciberkleid/hello-go; fi
cd hello-go/src
# To initialize, run: go mod init example.com/hello; go test
unset HELLO_ARG

# Start demo
cp ../Dockerfiles/Dockerfile .
clear
@_ECHO_ON

ls
bat Dockerfile
docker build . -t hello
docker images
docker run hello
docker run hello hello
docker run hello hello world of wonders
docker run hello hello "world of wonders"
@_SKIP# Guaranteed: same OS, package installed, binary in PATH

cp ../Dockerfiles/* .; clear
# launch behavior
catd Dockerfile Dockerfile-1
docker build . -t hello -f Dockerfile-1
docker run hello
docker run --init -e TINI_KILL_PROCESS_GROUP=1 hello world of wonders

clear
# OS signals
bat Dockerfile-2
docker build . -t hello -f Dockerfile-2
docker run hello world of wonders

clear
# layers/caching
docker images
docker history hello
bat Dockerfile-2
bat Dockerfile-3
@_SKIP# Talk about COPY command location, OS package commands, single command for dependencies and source
time docker build . -t hello -f Dockerfile-3 --no-cache
sed -i '' 's/Hello/Greetings/g' hello.go
time docker build . -t hello -f Dockerfile-3
