@_ECHO_OFF
tabname dockerfile-go
SAVED_DEMO_DELAY=${DEMO_DELAY}
export BAT_LANG_FLAG="-l Dockerfile"
export DOCKER_BUILDKIT=0
dclean
cd ${DEMO_TEMP}

# Set up demo files
go clean -x -modcache
if [ ! -d hello-go ]; then git clone git@github.com:ciberkleid/hello-go; fi
cd hello-go/src
# To initialize, run: go mod init example.com/hello; go test
unset HELLO_ARG

# Start demo
clear
@_ECHO_ON

ls
# traditional
go version
go install
@_SKIPls -lrt $GOPATH/pkg/mod/*/* | tail -n1
@_SKIPls -ltr $GOPATH/bin | tail -n1
find $GOPATH \( -name "strutil@*" -o -name hello \) -ls
hello
hello world
hello world of wonders
hello "world of wonders"
@_SKIP# Talk about expectations of prod: same OS? package installed? binary in PATH?
@_SKIP# Works on my machine... ¯\_(?)_/¯
# Works on my machine... \_(?)_/

cp ../Dockerfiles/* .; clear
# containerize
bat Dockerfile
docker build . -t hello
docker images
docker run hello
docker run hello hello
docker run hello hello world of wonders
docker run hello hello "world of wonders"
@_SKIP# Guaranteed: same OS, package installed, binary in PATH

clear
# launch behavior
catd Dockerfile Dockerfile-1
docker build . -t hello -f Dockerfile-1
docker run hello
docker run --init -e TINI_KILL_PROCESS_GROUP=1 hello world of wonders

clear
# OS signals
bat Dockerfile-2
@_ECHO_OFF
export BAT_LANG_FLAG="-l sh"
@_ECHO_ON
bat run.sh
@_ECHO_OFF
export BAT_LANG_FLAG="-l Dockerfile"
@_ECHO_ON
docker build . -t hello -f Dockerfile-2
docker run hello
docker run hello world of wonders

clear
# layers/caching
docker images
docker history hello
bat Dockerfile-2
bat Dockerfile-3
@_SKIP# Talk about COPY command location, OS package commands, single command for dependencies and source
time docker build . -t hello -f Dockerfile-3 --no-cache
sed -i '' 's/Hello/Greetings/g' hello.go
time docker build . -t hello -f Dockerfile-3
