@_ECHO_OFF
tabname dockerfile-2
export DOCKER_BUILDKIT=0
SAVED_DEMO_DELAY=${DEMO_DELAY}
dclean2

export BAT_LANG_FLAG="-l Dockerfile"

# Set up go demo
mkdir -p ${DEMO_TEMP}/hello-go
cd ${DEMO_TEMP}/hello-go
# Copy everything, including hidden files
#cp -r ${DEMO_FILES}/hello-go/. .
# Copy everything, excluding hidden files
cp -r ${DEMO_FILES}/hello-go/* .
rm hello.go
docker pull golang

# Set up to start demo
cd ${DEMO_TEMP}/hello-go
clear
@_ECHO_ON

go run hello-box.go everyone
ls *go*

echo -e "FROM scratch" | docker build . -f-
ls
@_SKIPdu -hs * | sort -h
@_ECHO_OFF
export BAT_LANG_FLAG="-l exclude"

@_ECHO_ON
cp ${DEMO_FILES}/hello-go/.dockerignore .; bat .dockerignore
@_ECHO_OFF
export BAT_LANG_FLAG="-l Dockerfile"
export DEMO_DELAY=0
@_ECHO_ON
echo -e "FROM scratch" | docker build . -f-
@_ECHO_OFF
export DEMO_DELAY=${SAVED_DEMO_DELAY}
@_ECHO_ON

clear
bat Dockerfile-4
@_SKIPtime docker build . -f Dockerfile-4 -t hello --no-cache
@_SKIPsed -i '' 's/Hello/Greetings/g' hello-box.go
@_SKIPtime docker build . -f Dockerfile-4 -t hello
bat Dockerfile-5
time docker build . -f Dockerfile-5 -t hello
@_SKIPsed -i '' 's/Greetings/Hi/g' hello-box.go
sed -i '' 's/Hello/Greetings/g' hello-box.go
@_SKIPtime docker build . -f Dockerfile-5 -t hello
@_ECHO_OFF
export DEMO_DELAY=0
@_ECHO_ON
time docker build . -f Dockerfile-5 -t hello
@_ECHO_OFF
export DEMO_DELAY=${SAVED_DEMO_DELAY}
@_ECHO_ON

clear
# tags
bat Dockerfile-6
echo -e "FROM golang" | docker build . -f- -t demo:1.6 -t demo:1 -t demo
docker images | grep demo
