# Multi-stage example: copy binary to smaller image

FROM golang AS build
WORKDIR /app
COPY *go* ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -a -installsuffix cgo -o hello

FROM scratch
COPY --from=build /app/hello /
ENTRYPOINT ["/hello"]
CMD ["world"]

