# Pulls versioned buildpacks from GCR
# Pulls build and run images from localhost:5000

buildpacks = [
  { id = "paketo-buildpacks/apache-tomcat",              image = "gcr.io/paketo-buildpacks/apache-tomcat:1.1.4" },
  { id = "paketo-buildpacks/azure-application-insights", image = "gcr.io/paketo-buildpacks/azure-application-insights:1.2.0" },
  { id = "paketo-buildpacks/bellsoft-liberica",          image = "gcr.io/paketo-buildpacks/bellsoft-liberica:2.5.4" },
  { id = "paketo-buildpacks/debug",                      image = "gcr.io/paketo-buildpacks/debug:1.2.4" },
  { id = "paketo-buildpacks/dist-zip",                   image = "gcr.io/paketo-buildpacks/dist-zip:1.3.1" },
  { id = "paketo-buildpacks/encrypt-at-rest",            image = "gcr.io/paketo-buildpacks/encrypt-at-rest:1.2.4" },
  { id = "paketo-buildpacks/executable-jar",             image = "gcr.io/paketo-buildpacks/executable-jar:1.2.4" },
  { id = "paketo-buildpacks/google-stackdriver",         image = "gcr.io/paketo-buildpacks/google-stackdriver:1.2.0" },
  { id = "paketo-buildpacks/gradle",                     image = "gcr.io/paketo-buildpacks/gradle:1.2.1" },
  { id = "paketo-buildpacks/image-labels",               image = "gcr.io/paketo-buildpacks/image-labels:1.0.4" },
  { id = "paketo-buildpacks/jmx",                        image = "gcr.io/paketo-buildpacks/jmx:1.1.4" },
  { id = "paketo-buildpacks/maven",                      image = "gcr.io/paketo-buildpacks/maven:1.4.1" },
  { id = "paketo-buildpacks/procfile",                   image = "gcr.io/paketo-buildpacks/procfile:1.3.4" },
  { id = "paketo-buildpacks/sbt",                        image = "gcr.io/paketo-buildpacks/sbt:1.2.1" },
  { id = "paketo-buildpacks/spring-boot",                image = "gcr.io/paketo-buildpacks/spring-boot:1.5.4" },
#  { id = "paketo-buildpacks/dep",                        image = "gcr.io/paketo-buildpacks/dep:0.0.109" },
#  { id = "paketo-buildpacks/go-compiler",                image = "gcr.io/paketo-buildpacks/go-compiler:0.0.112" },
#  { id = "paketo-buildpacks/go-mod",                     image = "gcr.io/paketo-buildpacks/go-mod:0.0.96" },
]

[[order]]
group = [

### Order is strictly enforced
  { id = "paketo-buildpacks/bellsoft-liberica",          version="2.5.4" },
  { id = "paketo-buildpacks/gradle",                     version="1.2.1", optional = true },
  { id = "paketo-buildpacks/maven",                      version="1.4.1", optional = true },
  { id = "paketo-buildpacks/sbt",                        version="1.2.1", optional = true },

### Order determines precedence
  { id = "paketo-buildpacks/executable-jar",             version="1.2.4", optional = true },
  { id = "paketo-buildpacks/apache-tomcat",              version="1.1.4", optional = true },
  { id = "paketo-buildpacks/dist-zip",                   version="1.3.1", optional = true },
  { id = "paketo-buildpacks/spring-boot",                version="1.5.4", optional = true },
  { id = "paketo-buildpacks/procfile",                   version="1.3.4", optional = true },

### Order does not matter
  { id = "paketo-buildpacks/azure-application-insights", version="1.2.0", optional = true },
  { id = "paketo-buildpacks/debug",                      version="1.2.4", optional = true },
  { id = "paketo-buildpacks/google-stackdriver",         version="1.2.0", optional = true },
  { id = "paketo-buildpacks/jmx",                        version="1.1.4", optional = true },

### Order is strictly enforced
  { id = "paketo-buildpacks/encrypt-at-rest",            version="1.2.4", optional = true },
  { id = "paketo-buildpacks/image-labels",               version="1.0.4", optional = true },
]

#[[order]]
#group = [
#  { id = "paketo-buildpacks/go-compiler",               version="0.0.112", optional = true },
#  { id = "paketo-buildpacks/go-mod",                    version="0.0.96", optional = true },
#]
#
#[[order]]
#group = [
#  { id = "paketo-buildpacks/go-compiler",               version="0.0.112", optional = true },
#  { id = "paketo-buildpacks/go-dep",                    version="0.0.109", optional = true },
#]

[stack]
id          = "io.buildpacks.stacks.bionic"
build-image = "localhost:5000/build"
run-image   = "localhost:5000/run"